const tiposCaracterologicos = {
    "Colérico": {
        formula: "E.A.P",
        resumen: "Texto Resumen Colérico",
        caracteristicasGenerales: "Este tipo de persona se caracteriza por una necesidad constante e impulsiva de actividad, mostrando un ímpetu vital que necesita canalizar en acciones concretas. Es entusiasta, combativo, persuasivo y optimista, con una emotividad intensa que lo impulsa a emprender con energía, aunque muchas veces sin profundidad ni constancia. Sus sentimientos son fuertes y expansivos, con gran facilidad de palabra y una inclinación natural a expresar lo que piensa y siente. Reacciona con fogosidad, especialmente al enojarse, y ante las injurias responde con violencia verbal e incluso física sin necesidad de provocaciones repetidas. Se lanza con entusiasmo al peligro sin calcular mucho las consecuencias, y es muy exigente consigo mismo y con los demás, buscando corregir errores con firmeza. Tiene un marcado instinto de mando, dificultad para aceptar posiciones subordinadas, y una inteligencia rápida, intuitiva y aguda. Su apariencia suele reflejar su carácter: decidido, enérgico y con porte varonil.",
        aspectosPositivos: "Su naturaleza, fortaleza, audacia, y valentía le capacitan para grandes empresas. Es hombre de ideales elevados, a los que endereza su energía, y en ello no se queda contento con pequeñeces ni medianías. Todo lo capacita presupuestalmente otras cualidades de inteligencia, etc.,. Para desempeñar cargos de importancia en la vida social. Cuenta con una voluntad decidida y una amplitud de miras muy grande que le permite extender sus actividades a muy diversos campos. Ha sido este el carácter peculiar de muchos jefes, dadas las cualidades de mando y conquista, combinadas con un ánimo generoso y magnánimo. Apto para la política, la enseñanza, periodismo, la dirección de colectividades, tiene gran talento de improvisación y cualidades de orador. Con frecuencia organiza acertadamente las actividades del grupo social a que pertenece y en ellos sabe seducir con optimismo comunicativo. Aficionado al deporte, suele cosechar en el no pocos éxitos.",
        aspectosNegativos: "Su temperamento le lleva a vivir el instante presente, interesándose casi exclusivamente por los resultados inmediatos. Tiene además, un gran peligro de dispersión y derroche de su gran caudal vital, empezando muchas cosas sin acabarlas o comprometiéndose a más tareas de las que podría realizar; o desarrollando simultáneamente varias ocupaciones sin llevar bien ninguna de ellas. Bajo el dominio de su naturaleza impulsiva puede tomar fácilmente decisiones arriesgadas, que le conduzcan a situaciones comprometidas por no haber calculado con previsión las consecuencias. Su riqueza psicológica y el reconocimiento de su propia superioridad en la acción le pueden llevar muy fácilmente al orgullo, o por lo menos a la vanidad y al hacerle difícil el reconocer superiores. Confía en sí mismo, se basta a sí mismo y quiere imponer su voluntad a los demás, le cuesta reconocer sus defectos y fácilmente critica los ajenos, siendo indulgente consigo mismo y exigente con los demás. Puede llegar a defender sus defectos como si fueran buenas cualidades y aún a gloriarse de sus faltas. Esto hace que su caída sea ignominiosa, en seguida se desata la tempestad de cólera, que llega a veces hasta la crueldad, otro peligro en su acción, es el desear tan vivamente sus fines. ",
        normasAutoeducativas: "Dadas sus grandes posibilidades y peligros, así como su impulsividad, necesita más que ningún otro, de un consejero o director que le ayuda a mantener en la mejor línea de conducta, organizar su actividad y orientarla hacia ideales elevados. Para ello deberá luchar contra su natural inclinación hacia la independencia absoluta y ganar la batalla de la humildad y . mansedumbre. Estas virtudes contrapeso de sus peligros, les son esenciales. Adquiere el hábito de reflexionar siempre antes de obrar y decidir, no dejando arrastrarse del impulso ciego hacia la acción. Para ello tiene buena base en su natural talento y claridad de juicio, así como para apreciar las buenas cualidades de los demás, lo cual le hará comprensivo y amable, evitando las críticas injustas respecto al prójimo. La reflexión le ayudará a organizar su actividad, el dispersarse y agotarse, dándole profundidad y alejándose de la continua y superficial improvisación. Sepa descansar, leer, estudiar. Ello renovará sus fuerzas, ideales, dando paz y madurez a su vida interior. Tratándose de una orientación profesional, el tipo de carácter no resuelve totalmente dicha orientación. Hay que tener en cuenta los resultados de otras pruebas (Inteligencia, actitudes, etc.)."
    },
    "Pasional": {
        formula: "E.A.S",
        resumen: "Texto Resumen Pasional",
        caracteristicasGenerales: "Este tipo de persona es activa, constante y enérgica, pero con un exterior sereno. Vive en alta tensión interna que, si se desborda, puede estallar en reacciones violentas. Tiene gran iniciativa y dirección clara hacia metas definidas. Sus emociones son profundas y duraderas; la lealtad en la amistad es fuerte, pero también mantiene rencores y deseos de venganza si es herido repetidamente. Reflexivo ante el peligro, actúa con determinación según lo considere necesario. Es firme en sus decisiones, constante en la acción y puede llegar a ser testarudo. Tiene habilidad para organizar y liderar con eficiencia más que con simpatía. Es ordenado, sistemático y orientado a objetivos a largo plazo. Intelectualmente es amplio, con buena memoria e imaginación fecunda. Le atraen los temas morales, sociales, religiosos y filosóficos. Es honesto, confiable, fiel a su palabra y protector con los más débiles. Socialmente es correcto, digno y sencillo, sin recurrir a la diplomacia falsa ni a confrontaciones innecesarias.",
        aspectosPositivos: "Cuando se encausan hacia un ideal grande, es capaz de una consagración, abnegación y actividad extraordinaria. Su rigor lógico en el pensamiento, su memoria, su capacidad de invención y eficacia en la ejecución, le capacita para las grandes empresas, en cuya dirección de alta jefatura puede conseguir notables objetivos. Toma sus propios asuntos y los que le encomiendan con mucha seriedad y es de fiar cuando empeña su palabra o promete alguna cosa. En la dirección de los súbditos sabe unir la exactitud con la prudencia, aunque a veces le falta algo de simpatía atrayente; al final si es consecuente con su natural rectitud, se impone por justicia y nobleza. No olvida los favores y es agradecido. Es notable su poder de previsión y sentido de responsabilidad. Es un director o jefe nato, con tendencias efectivas y fundadas hacia los grandes planes y objetivos, es apto para casi todas las carreras superiores, menos apto para el arte.",
        aspectosNegativos: "Sus defectos presentan los mismos matices que sus buenas cualidades: grandes pasiones que no se borra fácilmente. Encuentra fuertes dificultades en sujetarse a un superior. Puede ser susceptible, crítico, desconfiado, así como volverse huraño y poco social si acentúa en sí su actitud espontánea de reserva. Cuando odia lo hace de corazón y difícil hacerle reconciliar con su enemigo. Tiende espontáneamente al rencor y la venganza. Otro de sus defectos capitales es la testarudez: cuando se forma el juicio sobre una cosa es casi imposible hacerle cambiar de parecer. Naturalmente, si se equivoca ha de atenerse a las consecuencias. Como su pasión con frecuencia le oscurece el juicio, sus críticas son severas y muchas veces injustas. Es también notable su amor propio, ya que no consiente ser vencido ni sobrepasado por nadie. No es raro que se note en él impaciencia respecto a los defectos ajenos y desconfianza hacia algunas personas. En la acción peca a menudo por exceso de energía, lo que le lleva a ser duro y exigente con los otros.",
        normasAutoeducativas: "Este tipo caracterológico, de lo más ricos en posibilidades, ha de utilizar sus energías, consiguiéndose su propio dominio y encausándose hacia la idea generosa y noble. Si desea efectuar una acción de veras fecunda y benéfica, debe de luchar por conseguir, sobre todo la humildad, suavidad y comprensión benévola de las limitaciones ajenas, así como de sus cualidades. A ello le ayudará su natural claridad de juicio y su capacidad de reflexión. Temple su ánimo con la contemplación sosegada y tranquila de la naturaleza. Sobre todo cuando haya reconcentrado por largo tiempo. Cultive algún deporte: especialmente le ayudará la natación y el excursionismo. No rehuya el pedir consejo de un director que, a ser posible, se distinga por su seriedad."
    },
    "Nervioso": {
        formula: "E.NA.P",
        resumen: "Texto Resumen Nervioso",
        caracteristicasGenerales: "Persona emocionalmente intensa, con sentimientos abundantes pero muy cambiantes y de escasa duración. Su vitalidad es desordenada y su vida interior compleja, llena de tensiones, goces y sufrimientos que lo llevan a centrarse en sí mismo. Tiene una imaginación muy viva, gran facilidad de palabra y talento artístico, siendo muy sensible y sugestionable. Es impulsivo, curioso, fácilmente herido e irritable, pero sus reacciones suelen ser breves. Puede mostrarse rebelde y difícil en el trato cuando se siente ofendido, ya que tiende a exagerar los conflictos. Es inseguro, se asusta con facilidad, pero busca llamar la atención y ser admirado. Tiende a olvidar sus errores rápidamente y a sobrevalorarse. Su inteligencia es más intuitiva que lógica, concreta más que abstracta. Aunque activo y adaptable, le falta constancia para el esfuerzo prolongado. Es muy influenciable por su entorno, entiende bien a los demás y suele agradar con facilidad a quienes lo comprenden.",
        aspectosPositivos: "Tiene un corazón muy sensible a los males de los demás, así como los favores que se le hacen y atenciones de que es objeto. Es inclinado a la bondad compasión y sumamente generoso. Nadie tan atento como él respecto a las necesidades y gastos ajenos, con una servicialidad y espontaneidad cariñosa cuando trata con aquellos que admira o que sabe que le aprecian y quieren. Posee fino tacto y sabe ser diplomático cuando lo desea. Si le manda alguien a quien él aprecia como superior, es dócil y obediente. Su espíritu delicado le comunica una gracia y don especial para el trato. Poco aptos como él para consolar una persona abatida. Son notables por lo general, sus dotes de creación subjetiva y suele poseer un gusto exquisito para intuir el mensaje de los otros artistas.",
        aspectosNegativos: "Donde está la raíz de sus virtudes naturales, está también las de sus defectos: su sensibilidad. Los demás, para tratarle se ven sus sentimientos, se hacen insoportables a sus compañeros. Pueden llegar a ser tan susceptibles que si se le mira se siente herido porque le miramos; si no se le mira, por que se considera despreciado. Inclinado también, si no se domina, a la vanidad y a la sensualidad. Vive de impresiones, de ímpetus momentáneos; si se abandona a ellos no realizará nada grande y serio. Prefiere improvisar y es enemigo de todo lo que exija esfuerzo y disciplina-metódica (mental o física). Esta inconstancia es su defecto principalmente; además por tal dependencia, de la impresión momentánea, fácilmente cambia de parecer y de ocupación, puede llegar a ser esclavo del momento presente (los que los otros dicen o hacen, bueno o malo)",
        normasAutoeducativas: "Necesita para su vida un dominio extraordinario si quiere tener un carácter que no esté expuesto a las situaciones del momento. Dominio de su imaginación para ver las cosas tales como son en la realidad. Convénzase de que la mayoría de sus males son producto de su imaginación. Debe por consiguiente, insistir mucho por la objetividad de sus juicios. Necesita también el dominio de su emotividad para no estar en el vaivén de cualquier excitante interno o externo; para no ser esclavo de sus afectos y no entregarlos a cualquiera, sino emplearlos al servicio de algo que le merezca, siempre de acuerdo con el plan vivido. Dominio de su inclinación a la inconstancia, a la superficialidad. Para esto, tenga siempre una ocupación seria (estudio, responsabilidad en algún trabajo, etc.) en la que debe poner todo empeño. Sea servicial y cariñoso con los demás, pero tenga en cuenta que no se debe dejar explotar por ellos con perjuicio propio. Procure adaptarse a la vida práctica conociendo el corazón humano y la psicología; esto le hará ver las cosas con más objetividad. Escoja, en general, lecturas que le hagan más sólido y reposado, y no las que exaltan la imaginación. Tratándose de una orientación profesional, el tipo de carácter no resuelve totalmente dicha orientación. Hay que tener en cuenta los resultados de otras pruebas."
    },
    "Sentimental": {
        formula: "E.NA.S",
        resumen: "Texto Resumen Sentimental",
        caracteristicasGenerales: "Persona de gran sensibilidad emocional y afectos profundos, aunque poco expresivos hacia el exterior. Interioriza mucho sus emociones, especialmente las negativas, como ofensas, que pueden acumularse hasta explotar con intensidad. Es leal y constante en la amistad, pero reservado, serio y propenso a la melancolía y la autocrítica. Tiene escasa energía para la acción y se siente limitado para expresar lo que siente, lo que lo lleva al aislamiento. Reflexivo, escrupuloso y con un fuerte sentido moral, tiende a la indecisión y al análisis excesivo. No es práctico ni dinámico, pero sí soñador, con inclinación hacia la escritura y lo literario. Ama lo profundo y lo serio, actúa con dulzura, es cumplidor del deber, perseverante y responsable. Aunque no se ofrece espontáneamente, está dispuesto a ayudar si se lo piden. Se adapta bien a trabajos que requieran silencio, dedicación y cuidado, y prefiere una vida sencilla y sin ostentaciones.",
        aspectosPositivos: "Sobresale en él la honradez y la bondad. Incapaz de ser cruel o áspero con otros, aunque exteriormente su reserva parezca apatía. Con frecuencia halla gusto especial en el cuidado de enfermos. Sencillo, humilde y fidedigno; poco inclinado a la sensualidad. Propenso a ayudar a los demás. Perseverante. Trabaja con profundidad y acepta generosamente sus obligaciones. Suele tener disposición para las matemáticas y lenguas y también para aquellas ciencias que requieren minucioso análisis de las acciones humanas. Abundan en este tipo los moralistas y pedagogos, psicólogos, etc., así como los literatos y críticos de arte.",
        aspectosNegativos: "Tiene el peligro de pecar siempre de defecto de indecisión ante un partido que hay que tomar. Tiende al desánimo y subestimar sus propias cualidades; con ello puede llegar a un pesimismo, amargura o timidez, molesta para sí mismo y para los demás, como compensación puede habituarse a juzgar y calificar interiormente al prójimo con falta de tolerancia. No es raro el peligro de orgullo y soberanía interior afectiva, como compensación también de ese sentirse inferior respecto a otros cuya acción y apariencia es más brillante.",
        normasAutoeducativas: "Para él es de gran importancia cuidar de sus impresiones desagradables no se agraven profundamente, sino que se vayan borrando con suavidad, sobre todo si se trata de sentimientos de enemistad y rencor. En la acción procurar no guiarse por los sentimiento (simpatías, antipatías) sino por la razón. En toda dificultad, no se deje abatir por la tristeza, procure no perderse en vanas fantasías o ensueños. Esté siempre ocupado con trabajo moderado, pero constante. Haga esfuerzos por exteriorizarse y ponerse en contacto con la realidad que lo circunda. Busque estímulo en la convivencia con sus compañeros, por lo que tiene alegría expansiva, de comunicación con otros, cultivo de autodominio y determinación activa. También le ayudará mucho encontrar un buen consejero con quien desahogarse, así éste a la intuitivo, comprensivo y benévolo."
    },
    "Sanguíneo": {
        formula: "NE.A.P",
        resumen: "Texto Resumen Sanguíneo",
        caracteristicasGenerales: "Se trata de una persona emocionalmente rica pero superficial, con sentimientos cambiantes y poco profundos. Es activa, alegre, conversadora, imaginativa y sociable. Disfruta de la compañía, la libertad, la música y los deportes, pero tiende a dejarse llevar por las apariencias y es algo superficial en sus juicios. Necesita estímulos constantes para mantenerse enfocado y suele abandonar si pierde el interés. Es generoso, pero le cuesta comprometerse del todo. Es efusivo, expresa todo lo que piensa y siente, y aunque puede reaccionar impulsivamente ante ofensas, se recupera con facilidad y retoma nuevos propósitos sin angustiarse.",
        aspectosPositivos: "Es persona de agradable trato en la vida social: afable, bondadoso, lleno de alegría y de buen humor, animoso y comunicativo, muy servicial y cortés con todos. Fácilmente cae en la cuenta de lo que le hace falta a los demás y con agrado presta su ayuda. Compasivo y misericordioso para con las debilidades y males ajenos. Posee notable sentido práctico e inteligencia intuitiva. Suele tener disposición para la música y gusto en los deportes. A veces tiene buenos dotes literarios (es descriptivo humorista, más que lírico y profundo). No se preocupa con angustias ni ahonda demasiado en los problemas. Tiene el tacto especial para responder a las faltas ajenas con delicadeza, pero con sinceridad. Amigo de decir siempre la verdad; poco partidario de simulaciones. No guarda rencores para con nadie. Perdona fácilmente. Muy dócil a las indicaciones de los superiores, con sencillez de espíritu. ",
        aspectosNegativos: "Su principal defecto suele ser la veleidad e inconstancia; muda fácilmente de parecer, desiste de sus primeros propósitos, no acaba los trabajos comenzados. Se deja llevar fácilmente de la apariencia, ilusionándose por cualquier cosa y lanzándose a ella sin premeditar sus conveniencias y desventajas. Ello lo puede hacer tremendamente superficial y alocado, sin densidad de pensamiento, al huir de la reflexión sobre los temas profundos. Su afán de placeres, de gozar de la vida puede hacerle esquivar todo aquello que requiera esfuerzo serio, preocupándose solo por lo que le gusta de momento sin pensar en el más allá. También es serio según su enfoque de vida, el egoísmo utilitario. Puede convertirse en un diplomático aprovechado y oportunista de generando en farsa exterior sus dotes de afabilidad, bondad y cortesía. Por su inclinación a la vanidad, le gusta hablar de sí mismo de sus obras que no posee las cualidades de otros, llegando a perder todo sentido de cooperación, y servicio social. Tampoco es raro que pierda el tiempo en galanteos y cortesías inútiles, así como también que se vea en peligros morales difíciles de superar si se abandona a su afán de diversión y aventuras.",
        normasAutoeducativas: "Su mejor victoria ha de ser acostumbrarse, a reflexionar mucho y dar solidez a sus principios religiosos y morales. Propóngase meditar y pensar muy bien lo que va hacer y así obrar no arrastrado por el gusto ni por los primeros ímpetus, sino gobernado por la razón. De esta manera adquirirá mas consistencia interior, más bases en sus juicios, más constancia en la acción. La seriedad en los estudios le ayudará mucho a ser reflexivo, los mismos deportes con la disciplina que exigen, le serán muy provechosos propóngase en su actividad objetivos fijos y concretos. Después no los cambie ante la primera ocurrencia o dificultad en contra. Por otra parte, es necesario que se decida a modificar sus sentimientos con gran empeño, sino quiere llegar a extremos muy lamentables. Le ayudará mucho su predisposición natural a la bondad así como el consejo de un buen director. Importante es que no se deje llevar por cualquiera a primera vista, parezca atrayente y simpático, sino por los buenos cumplidores, del deber, que tengan una personalidad más sólida y seria. Fomente y desarrolle sus excelentes dotes de servicialidad y trato amable, huyendo del egoísmo para hacer grata la existencia de los demás."
    },
    "Flemático": {
        formula: "NE.A.S",
        resumen: "Texto Resumen Flemático",
        caracteristicasGenerales: "Se describe a una persona con una personalidad estructurada y energía constante. Es tranquila, paciente, reservada, poco expresiva en lo afectivo y con apariencia de frialdad. Prefiere el orden, la rutina y evita lo social, aunque es leal a sus amistades. Tiene una mente lógica, clara y curiosa, aunque su curiosidad depende de sus intereses previos. Destaca en ciencias y materias argumentativas, pero no en lo literario o narrativo. Es reflexivo, prudente y muy moral, actúa con constancia y conforme a sus principios. Aunque lento al decidir, una vez que lo hace, se entrega al trabajo con seriedad. Es ahorrador, honrado, sobrio y no se altera con facilidad. No es sensual ni vanidoso, y tiene escasa inclinación artística o imaginativa. En resumen, es una persona racional, disciplinada y fiable, con gran sentido del deber y poca inclinación emocional.",
        aspectosPositivos: "Suele ser notable su tranquilidad, en recibir los acontecimientos sin angustiarse por las dificultades ni preocuparse inútilmente. Conserva fácilmente el equilibrio entre el pensar y el obrar; entre el sentimiento y la acción. Sin pasiones violentas, es sobrio y moderado y no se deja llevar por los primeros impulsos, Amigo de la reflexión y de la consideración lenta, de los casos de pensamiento profundo en sus convicciones religiosas y criterios fundamentales. Paciente al tolerar a los demás, benevolente y amable, natural sencillo, sin ambiciones exageradas, no suele mentir. Lo que no logra por una actividad rápida lo alcanza por su constancia. Hombre práctico, le gustan las obligaciones netamente definidas. Obra por convicción y es valeroso ante las pruebas más imprevistas. Apto para todo lo que requiera orden y constancia, tiene por ello dotes de gran colaborador. Esto y su hondo sentido del deber le capacitan para cargos directivos de gran responsabilidad social y delicada administración. En sus trabajos suele ser eficiente, seguro y asiduo, muy puntual.",
        aspectosNegativos: "Su tranquilidad sentimental puede degenerar a veces en una especie de apatía, despreocupándose por todo y sin mostrar interés por alguna cosa. Ello puede endurecer notablemente su corazón, haciéndole insensible y frío para con los demás, llevándole paulatinamente a un egoísmo calculador y al orgullo por autosuficiencia. Posible que exagere su prudencia y previsión hasta el extremo de no comenzar nada por pensar demasiado las posibles dificultades (tiende a ser esclavo de su organización y método), desaprovechando así las ocasiones propicias. Ello puede parecer paradójico en un carácter activo, puede hacerle perezoso, al rehuir la acción por evitar sus posibles fracasos o peligros, o sencillamente por defender su soledad y tranquilidad, e independencia del ajetreo y trato social. En estos casos suele refugiarse en la actividad mental prefiriendo sistemáticamente su acción exterior lo cómodo y fácil, alejándose de cuanto pueda parecerle difícil o arduo.",
        normasAutoeducativas: "No se deje engañar por el pensamiento siguiente No tengo pasiones violentas, luego lo mejor es dejarme llevar de mi equilibrio y paz caracterológica. Le seria fatal, pues asentaría los aspectos negativos, como hemos visto. Por el contrario, debe animarse, ser más enérgico, decidido, valiente y entusiasta. Propóngase realizar diariamente un acto de vencimiento costoso, de mortificación de servicio ajeno, templando así su ánimo y entrenándolo para la acción vigorosa. Sobre todo tenga cuidado de no dejarse dominar por la pereza, ni, sueñe despierto, que es la mejor manera de fomentar la inacción. Aproveche en cambio, su constancia y demás cualidades positivas que le capacitan para obras de verdadera valía. Como un antídoto de su tendencia al egoísmo pasivo (también de su autosuficiencia), y asimismo como ayuda para encausar sus buenas cualidades, acuda a un consejero que le comprenda. Este darse a los demás le costará, pues requiere en ocasiones de tratos frecuentes con los otros, así como una mortificación interior que rehuya los juicios tajantes y exigentes poco humanos."
    },
    "Amorfo": {
        formula: "NE.NA.P",
        resumen: "Texto Resumen Amorfo",
        caracteristicasGenerales: "Muy rara vez se halla realizada esta fórmula en toda su amplitud, plenitud y tiende a conjugarse con características de otros tipos, al acentuarse la emotividad o la actividad en el sujeto. Muy influenciable por el ambiente; optimista buenazo y amable en el trato, notablemente sugestionable, sociable, pero con tendencia a rehuir el esfuerzo personal que exigen los trabajos comunes. La falta de actividad en los tipos radicales y en el subtipo emotivo, se manifiesta por la pereza; en el subtipo activo, esta pereza esta disfrazada. Los primeros aceptan las actividades (no la organizan), se dejan llevar, etc., por el ambiente. Los del segundo tipo cumplen dócilmente un deber obligatorio, dejando el esfuerzo para el último momento. Se fatigan y tienen poco sentimiento de lo real. Gusta mucho del afecto del hogar, aunque no se siente atraído por la vida metódica y ordenada.",
        aspectosPositivos: "Son ordenadamente valientes, no con una valentía de conquista sino de pasividad y resistencia, imperturbable ante un peligro. Es una verdadera cualidad que puede engendrar estima de sí mismo y voluntad de afirmarse en algunos campos. Poseen una notable capacidad de acomodación, que puede aprovecharse muy bien cuando colaboran en tareas colectivas. Suelen tener entendimiento práctico y son de extrema sociabilidad, necesitan de los otros para actuar, lo hacen con gusto y no pocas veces con verdadera aptitud en el arte escénico, con frecuencia poseen dotes de ejecución musical.",
        aspectosNegativos: "El defecto más notable es la pereza. Por eso deja el esfuerzo para último momento, hasta que la necesidad la obligue, naturalmente, esto le hace frecuentemente incumplidor e impuntual. Muchas veces esta pereza depende de causas orgánicas (astenia constitucional o accidental) por el ambiente en que vive y ello puede ponerle en serios peligros, descuidado en la limpieza. Su inactividad es un obstáculo para la servicialidad, haciéndole cada vez egocéntrico. Tiene el peligro de volar siempre a ras de tierra, sin iniciativa y sin gustar del esfuerzo y sacrificio para un gran ideal.",
        normasAutoeducativas: "Dada su extrema sociabilidad, le son muy convenientes los deportes y los campamentos juveniles (scoutismo, etc.), para hallar los valores ocultos que posee. Además los campamentos (scouts y similares) le ayudarán a adquirir cierto dominio de la realidad (desde hacer un nudo y cocinar hasta tener la responsabilidad de alguna actividad colectiva). Debe exigirse puntualidad y orden en sus cosas, claridad de palabra en sus conversaciones, puesto que tiende a hablar con el menor dispendio posible de la palabra. Evite la rutina y no se deje dominar por su horror a toda nueva tarea. Su tendencia a la ociosidad lleva consigo peligros sensuales que debe combatir vigorosamente. Le ayudará mucho proponerse resultados concretos inmediatos, rápidos, sensibles y buscar un buen consejero. Necesita buena orientación y una educación que le haga sobreponerse así mismo y aficionarse a la actividad."
    },
    "Apático": {
        formula: "NE.NA.S",
        resumen: "Texto Resumen Apático",
        caracteristicasGenerales: "La persona presenta baja vitalidad y una tendencia natural al aislamiento, no por rebeldía sino por falta de interés afectivo hacia los demás. Prefiere la soledad, la vida tranquila y sin agitación social. Es equilibrado, de humor estable y aparentemente dócil, aunque su docilidad proviene más de una baja tensión emocional que de verdadera sumisión. No suele sentir simpatía por otros, pero tampoco muestra antipatía activa. Tiene una inclinación hacia lo teórico más que lo práctico, y se adapta lentamente a nuevas costumbres. Si se forma en un entorno positivo, desarrolla buenos hábitos; pero si el entorno es negativo, corre el riesgo de adoptar malas conductas, lo cual representa un riesgo importante para su desarrollo moral y social.",
        aspectosPositivos: "En la fórmula caracterológica aparece como elemento positivo la secundariedad (fijeza, arraigo, tenacidad). Es capaz de disciplina y regularidad por automatización de las influencias del medio ambiente en que vive. No suele chocar con los demás. Su campo predilecto es el de las abstracciones y le agradan las matemáticas más bien que las ciencias experimentales o trabajos prácticos. Suelen tener aficiones pictóricas (dibujo libre, etc.) y se encuentran bien en sus actividades, uniformes y tranquilas.",
        aspectosNegativos: "Se podrían reducir a la falta de dinamismo psíquico que casi siempre supone un desequilibrio del sistema neurovegetativo y por consiguiente, una probable insuficiencia endocrina, tiende a no preocuparse de sí mismo ni de sus compañeros, a vivir pasivamente. Pero hay peligro que se trate solo de un disfraz y en realidad carezca de interés y entusiasmo en su vida. También puede polarizarse su interés hacia un egocentrismo, cerrado en que solo atraiga su bienestar propio, cuidarse y gozar. Por eso tiende a no comprometerse en actividades altruistas, que exijan esfuerzo y sacrificio.",
        normasAutoeducativas: "Debe reconocer que su solución radica principalmente en la adquisición de energía vital. Por lo tanto, su educación exige ante todos los remedios fisiológicos. Además debe procurarse destruir la inercia de su temperamento, con suavidad y progresivamente. Como naturalmente tiende a proceder en virtud de los hábitos adquiridos, estos debe de llenarlos con vitalidad propia. Es necesario que sus obras y acciones sean sensibles y personales; que se vinculen de alguna manera a su ser. Para ello le ayudará el ocuparse en métodos activos, trabajos en equipo. A medida que se vayan despertando en él algunos centros de interés. La afectividad se moviliza y entonces debe procurarse ideales concretos y próximos. Ha de conseguir introducirse, en un circulo afectuoso de buenos amigos y fomentar con ellos los paseos, excursiones, etc., así como combatir su egocentrismo, pasivo, mediante obras de beneficencia que exijan esfuerzo, dinámico en servicio del prójimo."
    }
};

export default tiposCaracterologicos;